name: Build in CI

on: [push]

env:
  LLVM_VERSION: 19.1.0

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-x64, macos-arm64 ]
        include:
          - os: macos-x64
            runner: macos-13
            targets_to_build: 'X86'
            build-args: '-j$(sysctl -n hw.ncpu)'
          - os: macos-arm64
            runner: macos-latest
            targets_to_build: 'AArch64'
            build-args: '-j$(sysctl -n hw.ncpu)'
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: jwlawson/actions-setup-cmake@v2.0.2
        with:
          cmake-version: "3.20"
      - name: Pull the latest packages
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VERSION/clang-$LLVM_VERSION.src.tar.xz
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VERSION/llvm-$LLVM_VERSION.src.tar.xz
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VERSION/clang-tools-extra-$LLVM_VERSION.src.tar.xz
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VERSION/cmake-$LLVM_VERSION.src.tar.xz

      - name: Extract packages
        run: |
          tar -xJf clang-$LLVM_VERSION.src.tar.xz
          tar -xJf llvm-$LLVM_VERSION.src.tar.xz
          tar -xJf clang-tools-extra-$LLVM_VERSION.src.tar.xz
          tar -xJf cmake-$LLVM_VERSION.src.tar.xz
      
      - name: Rename folders
        run: |
          mv clang-$LLVM_VERSION.src clang
          mv llvm-$LLVM_VERSION.src llvm
          mv clang-tools-extra-$LLVM_VERSION.src clang-tools-extra
          mv cmake-$LLVM_VERSION.src cmake

      - name: Prepare build folder
        run: | 
          mkdir build
          
      - name: Configure CMake
        run: |
          cd build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$PWD/built-ready-${{ matrix.os }} \
          -DCLANG_BUILD_TOOLS=ON -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" \
          -DLLVM_TARGETS_TO_BUILD="${{ matrix.targets_to_build }}" \
          -DLLVM_INCLUDE_EXAMPLES=0 \
          -DLLVM_INCLUDE_BENCHMARKS=0 \
          -DLLVM_INCLUDE_TESTS=0 \
          ../llvm

      - name: Build Clang-Tidy
        run: |
          cmake --build build ${{ matrix.build-args }} --target clang-tidy

      - name: Install Clang-Tidy
        run: |
          cmake --build build --target install-clang-tidy

      # - name: Temporary step to test packaging
      #   run: |
      #     mkdir -p $PWD/build/built-ready/bin/ && touch $PWD/build/built-ready/bin/clang-tidy

      - name: Archive binary
        run: |
          tar -czvf tool-clang-tidy-${{ matrix.os }}-$LLVM_VERSION.tar.gz $PWD/built-ready-${{ matrix.os }}/bin/clang-tidy
          ls -al

      - name: Attach artifact
        uses: actions/upload-artifact@v3
        with:
          name: tool-clang-tidy-${{ matrix.os }}
          path: tool-clang-tidy-${{ matrix.os }}-$LLVM_VERSION.tar.gz
          retention-days: 15
